/// Flutter icons No_meals
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  No_meals
///      fonts:
///       - asset: fonts/No_meals.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class No_meals {
  No_meals._();

  static const _kFontFam = 'No_meals';
  static const _kFontPkg = null;

  static const IconData no_meals_24px = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
